apiVersion: apps/v1
kind: Deployment
metadata:
  name: comment
spec:
  selector:
    matchLabels:
      app: comment
  template:
    metadata:
      labels:
        app: comment
    spec:
      containers:
      - name: comment
        image: davidyap/udemy-section2-comment
        ports:
        - containerPort: 8080
        env:
          - name: REACT_APP_PORT
            value: "8080"
          - name: REACT_APP_EVENT_BUS_LINK
            value: "http://event-bus:8080"

---
apiVersion: v1
kind: Service
metadata:
  name: comment
spec:
  selector:
    app: comment
  ports:
  - port: 8080
    targetPort: 8080
  type: ClusterIP
