apiVersion: apps/v1
kind: Deployment
metadata:
  name: posts
spec:
  selector:
    matchLabels:
      app: posts
  template:
    metadata:
      labels:
        app: posts
    spec:
      containers:
      - name: posts
        image: davidyap/udemy-section2-post
        ports:
        - containerPort: 8080
        env:
          - name: REACT_APP_EVENT_BUS_LINK
            value: "http://event-bus:8080"
---
apiVersion: v1
kind: Service
metadata:
  name: posts
spec:
  selector:
    app: posts
  ports:
  - port: 8080
    targetPort: 8080
  type: ClusterIP