apiVersion: apps/v1
kind: Deployment
metadata:
  name: query
spec:
  selector:
    matchLabels:
      app: query
  template:
    metadata:
      labels:
        app: query
    spec:
      containers:
      - name: query
        image: davidyap/udemy-section2-query
        ports:
        - containerPort: 8080
        env:
          - name: REACT_APP_PORT
            value: "8080"

---
apiVersion: v1
kind: Service
metadata:
  name: query
spec:
  selector:
    app: query
  ports:
  - port: 8080
    targetPort: 8080
  type: ClusterIP
