apiVersion: apps/v1
kind: Deployment
metadata:
  name: posts
spec:
  selector:
    matchLabels:
      app: posts
  template:
    metadata:
      labels:
        app: posts
    spec:
      containers:
      - name: posts
        image: davidyap/udemy-section2-post
        ports:
        - containerPort: 8080
        env:
          - name: REACT_APP_EVENT_BUS_LINK
            value: "http://event-bus:8080"
---
apiVersion: v1
kind: Service
metadata:
  name: posts
spec:
  selector:
    app: posts
  ports:
  - port: 8080
    targetPort: 8080
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: event-bus
spec:
  selector:
    matchLabels:
      app: event-bus
  template:
    metadata:
      labels:
        app: event-bus
    spec:
      containers:
      - name: event-bus
        image: davidyap/udemy-section2-event-bus
        ports:
        - containerPort: 8080
        env:
          - name: REACT_APP_PORT
            value: "8080"
          - name: REACT_APP_POST_LINK
            value: "http://posts:8080"

---
apiVersion: v1
kind: Service
metadata:
  name: event-bus
spec:
  selector:
    app: event-bus
  ports:
  - port: 8080
    targetPort: 8080
  type: ClusterIP

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: comment
spec:
  selector:
    matchLabels:
      app: comment
  template:
    metadata:
      labels:
        app: comment
    spec:
      containers:
      - name: comment
        image: davidyap/udemy-section2-comment
        ports:
        - containerPort: 8080
        env:
          - name: REACT_APP_PORT
            value: "8080"
          - name: REACT_APP_EVENT_BUS_LINK
            value: "http://event-bus:8080"

---
apiVersion: v1
kind: Service
metadata:
  name: comment
spec:
  selector:
    app: comment
  ports:
  - port: 8080
    targetPort: 8080
  type: ClusterIP

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: query
spec:
  selector:
    matchLabels:
      app: query
  template:
    metadata:
      labels:
        app: query
    spec:
      containers:
      - name: query
        image: davidyap/udemy-section2-query
        ports:
        - containerPort: 8080
        env:
          - name: REACT_APP_PORT
            value: "8080"

---
apiVersion: v1
kind: Service
metadata:
  name: query
spec:
  selector:
    app: query
  ports:
  - port: 8080
    targetPort: 8080
  type: ClusterIP

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: react-client
spec:
  selector:
    matchLabels:
      app: react-client
  template:
    metadata:
      labels:
        app: react-client
    spec:
      containers:
      - name: react-client
        image: davidyap/udemy-section2-client
        ports:
        - containerPort: 8080
        env:
          - name: REACT_APP_PORT
            value: "3000"
          - name: REACT_APP_COMMENT_LINK
            value: "http://comment:8080"
          - name: REACT_APP_POST_LINK
            value: "http://posts:8080"
          - name: REACT_APP_QUERY_LINK
            value: "http://query:8080"

---
apiVersion: v1
kind: Service
metadata:
  name: react-client
spec:
  selector:
    app: react-client
  ports:
  - port: 3000
    targetPort: 3000
  type: ClusterIP

---
apiVersion: v1
kind: Service
metadata:
  name: react-client-nodeport
spec:
  selector:
    app: react-client
  ports:
  - port: 3000
    targetPort: 3000
  type: NodePort
